version: '1'

services:
  backend:
    build:
      context: ./
      dockerfile: ./DockerfileServer
    image: "dmurphy1217/twitter-sentiment-backend"
    ports:
      - "4000:4000"
  frontend:
    build:
      context: ./
      dockerfile: ./DockerfileClient
    image: "dmurphy1217/twitter-sentiment-frontend"
    ports:
      - "3000:3000"